blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.allblogs, name="allblogs"),
    path('<int:blog_id>/', views.blog, name="blog"),
]

expsum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.expsum, name="expsums"),
    path('<int:year>/<int:month>/<int:day>/', views.expsum, name="expsums_parameters"),
]

frasometre/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.allgames, name="allgames"),
    path('game/<int:game_id>/', views.game, name="game"),
]

jobs/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views, api

urlpatterns = [
    path('view', views.home, name="alljobsview"),
    path('api/jobs', api.JobList.as_view()),
    path('api/jobs/<int:pk>/', api.JobDetail.as_view()),
    path('users/', api.UserList.as_view()),
    path('users/<int:pk>/', api.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

matrix/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.matrix, name="matrix"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import jobs.views
import jobs.urls
import blog.urls
import frasometre.urls
import expsum.urls
import matrix.urls
import twitter_broadcast.urls
import smart_rockets.urls
urlpatterns = [
                path('admin/', admin.site.urls),
                path('', jobs.views.home, name="home"),
                path('jobs/', include(jobs.urls)),
                path('blog/', include(blog.urls)),
                path('frasometre/', include(frasometre.urls)),
                path('expsum/', include(expsum.urls)),
                path('matrix/', include(matrix.urls)),
                path('twitter-broadcast/', include(twitter_broadcast.urls)),
                path('smart-rockets/', include(smart_rockets.urls)),
            ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

smart_rockets/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.smart_rockets, name="smart-rockets"),
]

twitter_broadcast/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.twitter_broadcast, name="twitter_broadcast"),
]

blog/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    title = models.TextField()
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    def summary(self):
        return self.body.split('. ')[0] + '.'

    def pub_date_pretty(self):
        return self.pub_date.strftime('%e %b %Y')

frasometre/models.py
from django.db import models


# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=800)
    image = models.ImageField(upload_to='images/frasometre/players', null=True, blank=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    image = models.ImageField(upload_to='images/frasometre/games', null=True, blank=True)
    title = models.TextField()
    summary = models.TextField(default='')
    date = models.DateField(default=models.DateTimeField)
    players = models.ManyToManyField(Player, null=True, blank=True, related_name='players')
    dungeonMasters = models.ManyToManyField(Player, null=True, blank=True, related_name='dungeon_masters')

    def __str__(self):
        return self.title


class Phrase(models.Model):
    phrase = models.TextField()
    time = models.DateTimeField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    players = models.ManyToManyField(Player)

    def joinedPlayerNames(self):
        return (', ').join(self.players.values().values_list('name', flat=True))

    def getTime(self):
        return self.time.strftime('%H:%M')

jobs/models.py
from django.db import models


# Create your models here.
class Job(models.Model):
    image = models.ImageField(upload_to='images/')
    summary = models.TextField(default='')
    title = models.TextField(default='')
    company = models.CharField(max_length=255, default='')
    start = models.DateField(default=None, blank=True, null=True)
    end = models.DateField(default=None, blank=True, null=True)

    def __str__(self):
        return self.company

smart_rockets/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Blog


# Create your views here.
def allblogs(request):
    blogs = Blog.objects
    return render(request, 'blog/allblogs.html', {'blogs': blogs})


def blog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/blog.html', {'blog': blog})

expsum/views.py
import datetime
from django.shortcuts import render


def expsum(request,
           year=datetime.datetime.now().year,
           month=datetime.datetime.now().month,
           day=datetime.datetime.now().day):
    return render(request, 'expsum/expsum.html', {'day': day, 'month': month, 'year': year})

frasometre/views.py
from django.shortcuts import render, get_object_or_404

from .models import Game


# Create your views here.
def allgames(request):
    games = Game.objects
    return render(request, 'frasometre/allgames.html', {'games': games})


def game(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    return render(request, 'frasometre/game.html', {'game': game})

jobs/views.py
from django.shortcuts import render


from .models import Job


# Create your views here.
def home(request):
    jobs = Job.objects
    return render(request, 'jobs/home.html', {'jobs': jobs})

matrix/views.py
from django.shortcuts import render


# Create your views here.
def matrix(request):
    return render(request, 'matrix/matrix.html')

smart_rockets/views.py
from django.shortcuts import render


# Create your views here.
def smart_rockets(request):
    return render(request, 'smart_rockets/smart-rockets.html')

twitter_broadcast/views.py
from django.shortcuts import render
from twitter_broadcast import twitter_reader as twt
from portfolio import settings as ls
from twitter_broadcast.tweet import *


# Create your views here.
def twitter_broadcast(request):
    twitter = twt.Twitter(ls.TWITTER_CREDENTIALS['consumerKey'],
                          ls.TWITTER_CREDENTIALS['consumerSecret'],
                          ls.TWITTER_CREDENTIALS['accessTokenKey'],
                          ls.TWITTER_CREDENTIALS['accessTokenSecret'])

    q = twitter.getUserTimeline('epsilonkeewee')
    tweets = []
    for item in q.get_iterator():
        print(item['user']['screen_name'], item)
        tweets.append(Tweet(item))

    return render(request, 'twitter_broadcast/index.html', {'tweets': tweets})

blog/templates/blog/allblogs.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Marc's Blog</title>

        <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


</head>

<body>
<header>
    {% include "jobs/nav_bar.html" with active_tab='blog' %}
</header>

<main role="main">
    <div class = "container">
        <h1 class="text-center pt-3">Welcome to Epsilonmajorquezero's Blog</h1>
        <br/>
        <br/>
        <h2>Latest Posts</h2>
        <hr/>
        {% for blog in blogs.all %}
            <a href="/blog/{{ blog.id }}" ><h3>{{ blog.title|safe }}</h3></a>
            {{ blog.pub_date_pretty }}
            <br/>
            <img class="rounded img-fluid" src="{{ blog.image.url }}" height="200" width="200"/>
            <br/>
            <p>{{ blog.summary|safe }}</p>
            <br/>
        {% endfor %}
    </div>

</main>

<div id="footer" class="navbar-fixed-bottom text-light bg-dark">
    <div class="container text-center">
        <p class="float-right">
            <a href="#" class="text-light">Back to top</a>
        </p>
        <p>&copy; Marc Espín {% now "Y" %}</p>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/blog.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{{ blog.title }}</title>

        <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


</head>

<body>
<header>
    {% include "jobs/nav_bar.html"  with active_tab='blog' %}
</header>

<main role="main">
    <div class = "container">
        <h1 class="text-center pt-3">{{ blog.title|safe }}</h1>
        <p class="text-center">{{ blog.pub_date }}</p>
        <img class="rounded img-fluid" src="{{ blog.image.url }}"/>
        <br/>
        <br/>
        <p class="text-justify rounded border border-dark px-2 py-2">{{ blog.body|linebreaksbr|safe }}</p>
    </div>

</main>

<div id="footer" class="navbar-fixed-bottom text-light bg-dark">
    <div class="container text-center">
        <p class="float-right">
            <a href="#" class="text-light">Back to top</a>
        </p>
        <p>&copy; Marc Espín {% now "Y" %}</p>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
</body>
</html>

frasometre/templates/frasometre/allgames.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Frasòmetre</title>

        <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Marc Espín</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="https://twitter.com/EpsilonKeewee">Twitter</a>
                <a class="nav-item nav-link" href="{% static 'CV_EN_Apr2018.pdf' %}">Resumee</a>
                <a class="nav-item nav-link" href="{% url 'allblogs' %}">Blog</a>
            </div>
        </div>
    </nav>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Frasòmetre Offtopic</h1>
            <p class="lead text-muted">Here be Dragons</p>
            <img class="img-fluid" src="{% static 'here_be_dragons.jpg' %}" height="400" width="400"/>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% for game in games.all %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        {% if game.image.url != None %}
                            <img class="card-img-top" src="{{ game.image.url }}"/>
                            <br/>
                        {% endif %}
                        <div class="card-body">
                            <a href="/frasometre/game/{{ game.id }}" ><h3>{{ game.title }}</h3></a>
                            {{ game.pub_date_pretty }}
                            <hr/>
                            <p class="card-text">{{ game.summary|linebreaksbr|safe }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</main>

<div id="footer" class="navbar-fixed-bottom text-light bg-dark">
    <div class="container text-center">
        <p class="float-right">
            <a href="#" class="text-light">Back to top</a>
        </p>
        <p>&copy; Marc Espín {% now "Y" %}</p>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
</body>
</html>

frasometre/templates/frasometre/game.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{{ game.title }}</title>

        <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">


</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Marc Espín</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="https://twitter.com/EpsilonKeewee">Twitter</a>
                <a class="nav-item nav-link" href="{% static 'CV_EN_Apr2018.pdf' %}">Resumee</a>
                <a class="nav-item nav-link active" href="{% url 'allblogs' %}">Blog</a>
            </div>
        </div>
    </nav>
</header>

<main role="main">
    <div class = "container">
        <h1 class="text-center pt-3">{{ game.title }}</h1>
        <p class="text-center">{{ game.date }}</p>
        {% if game.image.url != None %}
             <img class="img-fluid" src="{{ game.image.url }}"/>
        {% endif %}
        <br/>
        <br/>
        <p>{{ game.summary.body|linebreaksbr|safe }}</p>
        <hr/>
        {% if game.phrase_set.count > 0 %}
            {% for phrase in game.phrase_set.all %}
                <p>{{ phrase.phrase|linebreaksbr|safe }}</p>
                <p style="text-align:right">by {{ phrase.joinedPlayerNames }} <br>
                at {{ phrase.getTime }}
                </p>
            {% endfor %}
        {% endif %}
    </div>

</main>

<div id="footer" class="navbar-fixed-bottom text-light bg-dark">
    <div class="container text-center">
        <p class="float-right">
            <a href="#" class="text-light">Back to top</a>
        </p>
        <p>&copy; Marc Espín {% now "Y" %}</p>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
</body>
</html>

jobs/templates/jobs/nav_bar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Marc Espín</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="https://twitter.com/EpsilonKeewee">Twitter</a>
            <a class="nav-item nav-link" href="{% static 'CV_EN_Apr2018.pdf' %}">Resume</a>
            <a class="nav-item nav-link {% if active_tab == 'blog' %} active {% endif %}" href="{% url 'allblogs' %}">Blog</a>
            <a class="nav-item nav-link {% if active_tab == 'expsum' %} active {% endif %}" href="{% url 'expsums' %}">Exponential Sums</a>
            <a class="nav-item nav-link {% if active_tab == 'matrix' %} active {% endif %}" href="{% url 'matrix' %}">Matrix</a>
            <a class="nav-item nav-link {% if active_tab == 'smart_rockets' %} active {% endif %}" href="{% url 'smart-rockets' %}">Smart Rockets</a>
        </div>
    </div>
</nav>

matrix/templates/matrix/index.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Matrix</title>

        <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src='{% static 'p5.min.js' %}'></script>
    <script src="../../static/matrix.js"></script>

</head>

<body style="margin: 0; overflow: hidden;">
<header>
    {% include "jobs/nav_bar.html" with active_tab='matrix' %}
</header>
</body>
</html>

twitter_broadcast/templates/twitter_broadcast/tweet.html
<div class="text-justify rounded border border-dark px-2 py-2">
    {% if tweet.header != None %}
        <p>{{ tweet.header }}</p>
    {% endif %}
    <p>{{ tweet.text|safe }}</p>
</div>